# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    restart: unless-stopped
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/udp'
    command:
      - '--realm=${APP_SITE}'
      - '--server-name=turn-server'
      - '--fingerprint'
      - '--listening-ip=0.0.0.0'
#      - '--external-ip=${EXTERNAL_IP}'
#      - '--relay-ip=${EXTERNAL_IP}'
      - '--min-port=${MIN_PORT}'
      - '--max-port=${MAX_PORT}'
      - '--log-file=stdout'
#      - '--tls-listening-port=443'
      - '--use-auth-secret'
      - '--static-auth-secret=${STATIC_AUTH_SECRET}'
      - '--cli-password=${CLI_SECRET}'
      - --no-tls --no-dtls -n
      - --pidfile=/var/tmp/turnserver.pid
    tmpfs:
      - /run:mode=770,size=1k,uid=200,gid=10000
#    network_mode: host
    labels:
      - "traefik.http.services.app-${APP_TAG}.loadbalancer.server.port=3478"
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
