# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    restart: unless-stopped
    ports:
#      - 3478:3478
#      - 3478:3478/udp
#      - 5349:5349
#      - 5349:5349/udp
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/udp'
      - 127.0.0.1:5766:5766
    command:
      - -v
      - --log-file=stdout
      - --external-ip=$(detect-external-ip)
      - --realm=${APP_SITE}
      - --tcp-proxy-port=5555
      - --fingerprint
      - --listening-ip=0.0.0.0
#      - '--external-ip=${EXTERNAL_IP}'
#      - '--relay-ip=${EXTERNAL_IP}'
      - --min-port=${MIN_PORT}
      - --max-port=${MAX_PORT}
      - --log-file=stdout
      - --cli-ip=0.0.0.0
      - --use-auth-secret
      - --static-auth-secret=${STATIC_AUTH_SECRET}
      - --cli-ip=0.0.0.0
      - --cli-password=${CLI_SECRET}
      - --web-admin
      - --web-admin-listen-on-workers
      - --no-tls
      - --no-dtls
      - --pidfile=/var/tmp/turnserver.pid
      - -n
      - --psql-userdb="host=db dbname=${PGDATABASE} user=${PGUSER} password=${PGPASSWORD} sslmode=disable"
#    tmpfs:
#      - /run:mode=770,size=1k,uid=200,gid=10000
#    network_mode: host
    labels:
      - "traefik.http.services.app-${APP_TAG}.loadbalancer.server.port=5555"
      - "traefik.http.services.app-${APP_TAG}.loadbalancer.proxyprotocol=2"

    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
