# custom app config

version: '2'

services:
  app:
    image: ${IMAGE}:${IMAGE_VER}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /opt/src/dopos/cert-exp/ssl:/ssl:ro # traefik acme.json exported
    restart: unless-stopped
    ports:
## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
## STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
      - 7999:7999           # webadmin
      - 127.0.0.1:5766:5766 # cli
# Relay Ports
      - '${MIN_PORT}-${MAX_PORT}:${MIN_PORT}-${MAX_PORT}/udp'
    command:
      - -v
      - --realm=${APP_SITE}
      - --cert=/ssl/${APP_SITE}.crt
      - --pkey=/ssl/${APP_SITE}.key
      - --log-file=stdout
      - --external-ip=$(detect-external-ip)
      - --fingerprint
      - --listening-ip=0.0.0.0
      - --min-port=${MIN_PORT}
      - --max-port=${MAX_PORT}
      - --use-auth-secret
      - --static-auth-secret=${STATIC_AUTH_SECRET}
      - --cli-password=${CLI_SECRET}
      - --cli-ip=0.0.0.0
      - --web-admin
      - --web-admin-ip=0.0.0.0
      - --web-admin-port=7999
      - --user-quota=12
      - --total-quota=1200
      - --no-tlsv1
      - --no-tlsv1_1
      - --no-tcp-relay
      - --pidfile=/var/tmp/turnserver.pid
      - --psql-userdb="postgres://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}?sslmode=disable"
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes

networks:
  default:
    name: ${DCAPE_NET}
    external: true
