# app custom Makefile

APP_NAME ?= coturn

# The domain name of this homeserver.
APP_DOMAIN ?= dev.lan

# Hostname for external access
APP_SITE ?= coturn.dev.lan

# Docker repo & image name without version
IMAGE    ?= ghcr.io/coturn/coturn

#USE_TLS = yes

# ------------------------------------------------------------------------------
# app custom config

IMAGE_VER        ?= 4.6.1-alpine

#EXTERNAL_IP        ?= $(shell docker run --rm $(IMAGE):$(IMAGE_VER) detect-external-ip)
STATIC_AUTH_SECRET ?= $(shell < /dev/urandom tr -dc A-Za-z0-9 | head -c14; echo)
CLI_SECRET         ?= $(shell < /dev/urandom tr -dc A-Za-z0-9 | head -c14; echo)

MIN_PORT            = 49152
MAX_PORT            = 49200

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)


#EXTERNAL_IP=$(EXTERNAL_IP)
STATIC_AUTH_SECRET=$(STATIC_AUTH_SECRET)
CLI_SECRET=$(CLI_SECRET)

MIN_PORT=$(MIN_PORT)
MAX_PORT=$(MAX_PORT)

# Path to /opt/dcape/var. Used only outside drone
DCAPE_ROOT=$(DCAPE_ROOT)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

ext-ip:
	@echo $(EXTERNAL_IP)
